Implement event severity module
CodeTanzania/ewea-web pull request #137
Opened 2019-12-18 14:50 UTC by Mloweedgar

ref https://github.com/CodeTanzania/ewea/issues/16

2019-12-20 15:49 UTC, rijkerd commented on src/Home/index.js
>      description: modules.administrativeareas,
Change to module.administrativeAreas

2019-12-20 15:49 UTC, rijkerd commented on src/Home/index.js
>      description: modules.administrativeareas,
Change to administrativeAreas

2019-12-20 15:53 UTC, rijkerd commented on src/Events/components/EventSeverity/Form/index.js
> + * @description  Render form for creating a new event group
Rename to event severity

2019-12-20 16:02 UTC, rijkerd requested changes

2019-12-20 16:02 UTC, rijkerd commented on src/Events/components/EventSeverity/Form/index.js
> + * @description  Render form for creating a new event group
Rename to event severity

2019-12-20 16:02 UTC, rijkerd commented on src/Home/index.js
>      description: modules.administrativeareas,
Change to modules.administrativeAreas

2020-01-02 09:03 UTC, Mloweedgar commented
@BenMaruchu conflicts have been resolved, branch can be merged

2020-01-02 09:33 UTC, BenMaruchu approved these changes

2020-01-02 09:33 UTC, BenMaruchu commented
@Mloweedgar Can you resolve these conflicts?

2020-01-02 09:54 UTC, Mloweedgar commented
@BenMaruchu I have fixed the conflicts.

2020-01-02 14:45 UTC, merged