Implemented event certainty module
CodeTanzania/ewea-web pull request #138
Opened 2019-12-18 15:47 UTC by Mloweedgar

ref https://github.com/CodeTanzania/ewea/issues/16

2019-12-20 16:11 UTC, rijkerd requested changes

2019-12-20 16:11 UTC, rijkerd commented on src/Events/components/EventCertainty/Form/index.js
> + * @description  Render form for creating a new event group
Change to event certainty

2019-12-20 16:11 UTC, rijkerd commented on src/Events/components/EventCertainty/index.js
> +/* constants */
Remove this line

2019-12-20 19:20 UTC, BenMaruchu commented
@Mloweedgar can you also resolve conflicts on this branch

2020-01-02 08:44 UTC, Mloweedgar commented
@BenMaruchu conflicts have been resolved

2020-01-02 09:32 UTC, BenMaruchu approved these changes

2020-01-02 09:32 UTC, merged