Refactor event severity code base to follow new pattern
CodeTanzania/ewea-web pull request #166
Opened 2020-01-10 13:46 UTC by Mloweedgar

2020-01-10 14:03 UTC, BenMaruchu commented on src/Events/EventSeverity/index.js
> +              'An error occurred while archiving Focal Person, Please contact your system Administrator'
Supposed to be Severity not focal person

2020-01-10 14:12 UTC, BenMaruchu requested changes
Hello @Mloweedgar  can you work on the above reviews

2020-01-10 14:12 UTC, BenMaruchu commented on src/Events/EventSeverity/index.js
> +          () => notifySuccess('Focal Person was archived successfully'),
S
hould be updated to severity

2020-01-10 14:12 UTC, BenMaruchu commented on src/Events/EventSeverity/index.js
> +              'An error occurred while archiving Focal Person, Please contact your system Administrator'
Here also

2020-01-10 14:23 UTC, navish commented on src/Events/EventSeverity/index.js
> +   * @param {object} eventSeverity eventSeverity to be edited
Aside from variable names all other words are normal, do not convert them to camel case 
e.g. `@param {object} eventSeverity Event severity to be edited`

2020-01-10 14:24 UTC, navish requested changes
Aside from variable names all other words are normal, do not convert them to camel case

2020-01-16 13:19 UTC, BenMaruchu approved these changes

2020-01-16 13:19 UTC, merged