Refactor event certainty code base to follow new pattern
CodeTanzania/ewea-web pull request #179
Opened 2020-01-16 06:10 UTC by Mloweedgar

2020-01-16 13:23 UTC, BenMaruchu requested changes
@Mloweedgar  I have left you some review, please update when you get time

2020-01-16 13:23 UTC, BenMaruchu commented on src/Events/EventCertainty/index.js
> + * @description Render eventCertainty list which have search box, certainties and eventCertainty list
Please update `eventCertainty` to normal word like Event Certainties

2020-01-16 13:23 UTC, BenMaruchu commented on src/Events/EventCertainty/index.js
> +   * @description close eventCertainty form
here also

2020-01-16 13:23 UTC, BenMaruchu commented on src/Events/EventCertainty/index.js
> +   * @description Search EventCertainties List based on supplied filter word
Here also

2020-01-16 13:23 UTC, BenMaruchu commented on src/Events/EventCertainty/index.js
> +   * @description Handle on Edit certainty for list item
This should be `Edit Event Certainty`

2020-01-16 17:26 UTC, navish reviewed
Apart from @BenMaruchu comments, looks okay to me.

2020-01-28 14:27 UTC, BenMaruchu approved these changes

2020-01-28 14:28 UTC, merged